# POSTGRES_HOST = "172.17.0.1"
POSTGRES_HOST = 'pgdb'
POSTGRES_PORT = 5432
POSTGRES_USER = 'cooluser'
POSTGRES_PASS = 'coolpass'
POSTGRES_DB = 'cooldb'
POSTGRES_URI = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASS}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"